@baseUrl = http://localhost:3000


### Get all products

GET {{baseUrl}}/product HTTP/1.1


### Get product by ID

GET {{baseUrl}}/product/1 HTTP/1.1


### Create a new product

POST {{baseUrl}}/product HTTP/1.1
Content-Type: application/json

{
  "name": "Wireless Mouse",
  "category": "Electronics",
  "price": 20,
  "amount": 150
}


### Update product

PUT {{baseUrl}}/product/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Wireless Gaming Mouse",
  "category": "Gaming Accessories",
  "price": 25,
  "amount": 100
}


### Delete product

DELETE {{baseUrl}}/product/1 HTTP/1.1
